# Generated by Django 6.0.5 on 2026-05-26 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('raw_format', models.CharField(max_length=80)),
                ('status', models.CharField(default='complete', max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=120)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('record_kind', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground transport')], max_length=40)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=20)),
                ('activity_date', models.DateField()),
                ('service_period_start', models.DateField(blank=True, null=True)),
                ('service_period_end', models.DateField(blank=True, null=True)),
                ('location_code', models.CharField(blank=True, max_length=80)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('activity_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('activity_unit', models.CharField(max_length=20)),
                ('normalized_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emission_factor_name', models.CharField(blank=True, max_length=200)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('emissions_kg_co2e', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=100)),
                ('suspicion_flags', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('staged', 'Staged'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='needs_review', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.organization')),
            ],
            options={
                'ordering': ['-activity_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.reviewrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility portal'), ('travel', 'Travel platform')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('ingestion_mode', models.CharField(choices=[('csv_upload', 'CSV upload'), ('json_upload', 'JSON upload'), ('api_pull', 'API pull')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('external_system_ref', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.sourcesystem'),
        ),
        migrations.AddConstraint(
            model_name='reviewrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'source_record_id'), name='unique_source_record_per_org'),
        ),
    ]
